[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [ "_site/img", ".cache" ]

[[redirects]]
from = "/thingstodo"
to = "/visit"
status = 301
force = true

[[redirects]]
from = "/danceprof"
to = "/danceprofessional"
status = 301
force = true

[[redirects]]
from = "/showtime"
to = "/repertoire"
status = 301
force = true

[[redirects]]
from = "/danceaware"
to = "/popularising-the-arts/#danceaware"
status = 301
force = true

[[redirects]]
from = "/villageoutreach"
to = "/village-outreach"
status = 301
force = true

[[redirects]]
from = "/supportingartists"
to = "/kula-artistes-residence"
status = 301
force = true

[[redirects]]
from = "/popularisingarts"
to = "/popularising-the-arts"
status = 301
force = true

[[redirects]]
from = "/popularisingarts#vasant"
to = "/popularising-the-arts/#vasantahabba"
status = 301
force = true

[[redirects]]
from = "/popularisingarts#ajji"
to = "/popularising-the-arts/#ajji"
status = 301
force = true

[[redirects]]
from = "/vision"
to = "/about"
status = 301
force = true

[[redirects]]
from = "/artists/protima/*"
to = "/protima"
status = 301
force = true

[[redirects]]
from = "/4artists/protima/*"
to = "/protima"
status = 301
force = true

[[redirects]]
from = "/artists/surupa/*"
to = "/surupa"
status = 301
force = true

[[redirects]]
from = "/artists/bijayini/*"
to = "/bijayini"
status = 301
force = true

[[redirects]]
from = "/artists/rising/*"
to = "/pavithra"
status = 301
force = true

[[redirects]]
from = "/4artists/rising/*"
to = "/pavithra"
status = 301
force = true

[[redirects]]
from = "/artists/ensemble/*"
to = "/ensemble"
status = 301
force = true

[[redirects]]
from = "/expression/bnatyam/*"
to = "/gurukula"
status = 301
force = true

[[redirects]]
from = "/6expression/bnatyam/*"
to = "/gurukula"
status = 301
force = true

[[redirects]]
from = "/expression/odissi/*"
to = "/gurukula"
status = 301
force = true

[[redirects]]
from = "/6expression/odissi/*"
to = "/gurukula"
status = 301
force = true

[[redirects]]
from = "/soul/gurukul/*"
to = "/gurukula"
status = 301
force = true

[[redirects]]
from = "/soul/dream/*"
to = "/about"
status = 301
force = true

[[redirects]]
from = "/soul/future/*"
to = "/future"
status = 301
force = true

[[redirects]]
from = "/soul/philosophy/*"
to = "/about"
status = 301
force = true

[[redirects]]
from = "/passion/habba/*"
to = "/popularising-the-arts/#vasantahabba"
status = 301
force = true

[[redirects]]
from = "/passion/perform/*"
to = "/repertoire"
status = 301
force = true

[[redirects]]
from = "/reviews/*"
to = "/press"
status = 301
force = true
